### ISSUE TITLE
What's the purpose of the local Vagrant VM?

### ISSUE THREAD

**Issue by ianklatzco** [kevinnguy/dokku-aws-tutorial#1]
Thanks for this tutorial.

I'm guessing it's because have the local VM, you have a local dev environment, and you use the aws remote as a prod environment?

**Comment by kevinnguy** [comment]
No problem @ianklatzco! You're right that your local VM is your dev environment and that your remote environment is your prod environment. 

It's also useful to have a local VM that you can share with your team so that everyone shares the same dev environment.

**Comment by ianklatzco** [comment]
thank you very much!
